years:
  start: "2021-01-01"
  end: "2025-12-31"

cninfo:
  sleep_seconds: 1.2
  page_size: 30
  max_pages_per_firm: 10

keywords:
  core:
    - "搬迁"
    - "迁址"
    - "迁建"
    - "新建"
    - "扩产"
    - "投产"
    - "设立"
    - "落地"
    - "项目"
    - "产业园"
    - "基地"
    - "研发中心"
    - "研究院"
    - "区域总部"
    - "运营中心"
  overseas:
    - "海外"
    - "越南"
    - "泰国"
    - "墨西哥"
    - "东南亚"
